#!/bin/bash
set -e
set -o pipefail
DISPLAY= mplayer -vo aa:driver=curses:width=100:height=40 -monitoraspect 10:7 sunny-family-blowing-air-bubbl.mp4 -loop 0 -really-quiet | perl -p -e "s/\\n/[H[0;0H/" | node telnet-tv.js
