#!/bin/bash
[ -f aa.txt ] || DISPLAY= mplayer -vo aa:driver=linux:width=80:height=24 sunny-family-blowing-air-bubbl.mp4 -really-quiet -quiet | perl -p -e "s/\\n/[H/" >aa.txt
xterm -geometry 80x25 -e "cat aa.txt | pv -L 4K 2>/dev/null"
